name: ACR Id
description: Looks up an ACR's login server address given its resource group.
inputs:
  suffix:
    description: The suffx to apply to the names of artifacts.
    required : true
  configuration:
    description: The configuration to build.
    required: true
  build_version:
    description: The version number to apply to the build.
    required: true
  nuget_token:
    description: The token to setup with the NUGET_AUTH_TOKEN.
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          6.x
          7.x
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.nuget_token }}
    
    # Hack fix for https://github.com/NuGet/Home/issues/7503
    - name: Install dotnet tools
      shell: pwsh
      run: dotnet nuget list source

    - name: Install dependencies
      shell: pwsh
      run: dotnet restore
    
    - name: Build
      shell: pwsh
      run: dotnet build -p:Version=${{ inputs.build_version }} -p:ContinuousIntegrationBuild=True --configuration ${{ inputs.configuration }} --no-restore -p:TreatWarningsAsErrors=True --verbosity normal
    
    - name: Test
      shell: pwsh
      run: dotnet test NosePlug.Tests/NosePlug.Tests.csproj -p:BuildInParallel=false --no-build --configuration ${{ inputs.configuration }} --collect:"XPlat Code Coverage" --blame-hang --blame-hang-timeout 30s --blame-hang-dump-type Full --verbosity normal

    - name: TestResults
      if: always()
      uses: actions/upload-artifact@v3.1.3
      with:
          name: TestResults-${{ inputs.suffix }}
          path: NosePlug.Tests/TestResults

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.24
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'
        tag: '${{ github.run_number }}_${{ github.run_id }}'
        
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: CoverageReport-${{ inputs.suffix }}
        path: coveragereport